name: test/cli

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  make-target:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run cli tests
      run: make test/cli
