name: t_unit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  t_unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run t_unit
      run: make run/t_unit
