name: test/unit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  make-target:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run unit test
      run: make test/unit
