name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install cppcheck
      run: sudo apt install cppcheck
    - name: run lint
      run: make test/lint
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: test/build
      run: make build
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: test/unit
      run: make test/unit
  cli:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: test/cli
      run: make test/cli
