name: test/

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  make-target:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: test/build
      run: make all
    - name: test/cli
      run: make test/cli
    - name: test/unit
      run: make test/unit
