name: unittests

on:
  push:
    branches: [ master ]
    paths:
      - 'src/'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run unittests
      run: make run/utest
